// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccommodationBanner: typeof import("./src/components/AccommodationBanner.vue")["default"];
    AccommodationMenu: typeof import('./src/components/AccommodationMenu.vue')['default']
    AttractionBanner: typeof import('./src/components/AttractionBanner.vue')['default']
    AttractionIntro: typeof import('./src/components/AttractionIntro.vue')['default']
    CardAvatar: typeof import('./src/components/CardAvatar.vue')['default']
    CardImage: typeof import('./src/components/CardImage.vue')['default']
    CardText: typeof import('./src/components/CardText.vue')['default']
    CardWaterfall: typeof import('./src/components/CardWaterfall.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    GlobalSubtitle: typeof import('./src/components/GlobalSubtitle.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImgSrc: typeof import('./src/components/ImgSrc.vue')['default']
    IndexWeather: typeof import('./src/components/IndexWeather.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PaginationGroup: typeof import('./src/components/PaginationGroup.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export { }
